### ISSUE TITLE
Help with erros.

### ISSUE THREAD

**Issue by guinhx** [SummitRidgeEdu/Uni-Weapon-System#2]
I'm having several errors when using Single Action Weapon.
Could you record some video showing how to use it correctly, or add me to Discord to help me?
Discord: guinhx#2096

**Comment by SummitRidgeEdu** [comment]
I'm sorry I didn't write the README ...
This library assumes MackySoft's [Serialize Reference Extensions](https://github.com/mackysoft/Unity-SerializeReferenceExtensions).
I think that if you add it, the error will disappear.
